### ISSUE TITLE
Add higlight.js as module via Webpack

### ISSUE THREAD

**Issue by Dravere** [NodeBB/nodebb-plugin-markdown#103]
I saw in the commit history that you tried to add `highlight.js` as a module. Sadly they seem to only support Node style module via npm. Thus you reverted back to the previous type.

I'm considering achieving this in my fork of this plugin via [Webpack](https://webpack.js.org/). Webpack could repackage the `highlight.js` module to AMD. Which would then work with NodeBB. Is this something you would accept as a pull request?

Obviously this would mean that before every publish Webpack needs to be run, so the `higlight.js` is repackaged.

**Comment by julianlam** [comment]
Hah yes, I think I actually tried to implement highlight.js as an npm module **twice**. I forgot what happened the first time :man_facepalming: 

If you could achieve this with Webpack, I'd be grateful. I think we can use an npm prepublish script to invoke webpack to build a new highlight.js file, right?

**Comment by julianlam** [comment]
You seem to know what you're doing, I've added you as a collaborator to the repo. Don't go adding bitcoin miners or anything to the plugin, okay? :laughing:

**Comment by Dravere** [comment]
Haha ... no Bitcoin, gotcha, Dogecoin it is then :grin: 

I'll work out a proposal in a separate branch and submit a pull request. And yes I think it should work via prepbulish script. I'm still kind of new in Webpack and it is an intimidating tool.

**Comment by julianlam** [comment]
@Dravere, @barisusakli is working on implementing webpack in core, so this might be something that interests you. We're hoping to deprecate require.js and use webpack exclusively :grimacing:
