### ISSUE TITLE
How to add new languages in this plugin?

### ISSUE THREAD

**Issue by lslzl3000** [NodeBB/nodebb-plugin-markdown#214]
need more different type of codes, how to add new tags/languages?

**Comment by lslzl3000** [comment]
By the way, how to add language support for line numbers?
Should add line numbers for ts/typescript

**Comment by julianlam** [comment]
You can add new language support by adding the translated language keys into the public/languages folder

**Comment by lslzl3000** [comment]
I mean coding language, add new custom language definition

And for line numbers options, there is only 23 options in ACP settings, no 'typescript', so is there an option to add new languages in ACP?

**Comment by pitaj** [comment]
The JavaScript highlighting should work fine for typescript.

**Comment by lslzl3000** [comment]
> The JavaScript highlighting should work fine for typescript.

but no line numbers

**Comment by lslzl3000** [comment]
Can we enable line numbers for all 180+ languages from hightlights?

**Comment by julianlam** [comment]
No, that'd be an insane amount and increase the payload size of the minfile significantly... But I will take some languages into account.

**Comment by julianlam** [comment]
It occurs to me your complaint was regarding enabling _line numbers_ for TS, so that is now in #215.
