### ISSUE TITLE
Outdate version in NodeBB plugin management panel

### ISSUE THREAD

**Issue by lslzl3000** [NodeBB/nodebb-plugin-markdown#219]
The latest version in management panel is 10.1.1

![Screenshot 2023-02-18 at 10 11 49](https://user-images.githubusercontent.com/3398981/219826361-1d702db3-6ba1-458b-993b-3e34da6083c7.png)

**Comment by julianlam** [comment]
v10.1.1 is the latest version compatible with the v2.x release of NodeBB :smile:
