### ISSUE TITLE
[question] I think allow-html should sanitize the dangerous tags by default.

### ISSUE THREAD

**Issue by akhoury** [NodeBB/nodebb-plugin-markdown#58]
so if one allows HTML, by default, it should sanitize the dangerous tags, unless one chooses not to.

Basically, what I am suggesting is to combine both plugins, -markdown and -[sanitizehtml](https://github.com/akhoury/nodebb-plugin-sanitizehtml), where -markdown would uses the [sanitize-html](https://www.npmjs.com/package/sanitize-html) module.

The reason I think this is a not-so-bad idea is that a lot of the old-migrated forums have some subtle html tags in them, like `<p>`, `<br>`, `<strong>` - these are safe. Also, users now have the options to use things like `<table>` and `<img>` if they want to.

After all, HTML is still valid Markdown, at least for the <i>`<i>gfm</i>`</i>

**Comment by akhoury** [comment]
if you agree, I'll submit a PR

**Comment by julianlam** [comment]
If I understand you correctly, you want to add in sanitizehtml, so that if "Allow HTML" is ticked, then dangerous tags are *still* sanitised?

May be better to not bother using `markdown-it`'s HTML sanitisation and just use sanitizehtml throughout...

**Comment by akhoury** [comment]
> image script execution

really? like an XSS attack? do you have an example?

The only attacks I am aware of using images don't really depend of the tag, but rather on the URL, which is left-alone with the "markdownification". Some explained [here](http://security.stackexchange.com/a/8625/60997), and there is another where the img src would return a 401 and prompt the user to enter a username and password via basic auth - again, markdown-it can't really guard against these.

**Comment by julianlam** [comment]
We had `markdown-it` patched to not execute data-uris, I believe... a specially crafted one could execute code, though I could be mistaken as it's been awhile now.

**Comment by akhoury** [comment]
i see, we can always create a whitelist of allowed tags (vs a blacklist which we would need to keep up to date) - just like what would the sanitize-html would support as config.
![img](https://camo.githubusercontent.com/b561ac73b2d37e33a90348dced7b410725be7932/687474703a2f2f692e696d6775722e636f6d2f345655385353422e706e67)

This way, we can disallow any tags (or even attributes) that would cause a network request or could execute code. 
I don't know, whatever you think it's right.

**Comment by julianlam** [comment]
Core sanitizes tags by default now.
