### ISSUE TITLE
solarized-light.css should be solarized_light.css

### ISSUE THREAD

**Issue by paviro** [NodeBB/nodebb-plugin-markdown#78]
Syntax highlighting for me only works some times. Mostly after server restarts it just stops working for a couple of days/weeks and then some day kicks back in without any explanation.
Currently it does not work: https://forum.magicmirror.builders/topic/51/gpio-without-root/4

Any ideas? Using NodeBB v1.1.0 and the latest plugin version.

**Comment by paviro** [comment]
Seems like the css file is called `solarized-light.css` but the client tries to load `solarized_light.css `...

**Comment by julianlam** [comment]
Hi @paviro -- I totally did not see this (for apparently, almost two years)... is this still happening on latest? It works fine when solarized-light is selected for me.

**Comment by julianlam** [comment]
![selection_393](https://user-images.githubusercontent.com/923011/39778795-54d3c3c0-52d5-11e8-8af1-51a2fd7f031c.png)
